#NGINX_PORT, DOMAIN_NAMME et WORDPRESS_PORT 
#sont definie dans .env

#bloc server
server {
    #le ssl impose le chiffrement
    #IPv4
    listen ${NGINX_PORT} ssl;
    #le [::] veut dire qu on ecoute sur IPv6
    listen [::]:${NGINX_PORT} ssl;

    #en gros on peut se connecter a notre site que si on ecrit bien son
    #DOMAIN_NAME dans la barre de recherche
    server_name ${DOMAIN_NAME};


    #CHIFFREMENT TLSv1.2 et TLSv1.3
    #-----------------------------------------------------------------------
    #le serveur va choisir lui meme soit le 2 soit le 3
    #il va toujours prioritiser le plus recent (TLSv1.3)
    #ca va dependre de mon navigateur le quelle il va choisir
    #-------------------------------------------------------
    #emplacement du certificat public
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    #emplacement de le cle prive
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    #le chiffrement qu on utilise
    ssl_protocols TLSv1.2 TLSv1.3;
    #-------------------------------------------------------
    #POURQUOI NE PAS UTILISER LE SSL
    #parceque il a des vulnerabiliter cryptographique
    #-----------------------------------------------------------------------



    #dossier racine de notre site
    root /var/www/html;
    #la page index elle va se montrer par defaut
    index index.php;

    #quand qqn va se balader dans notre site 
    #try file va essayer de trouver le fichier exact
    #si elle trouve pas c est la page index qu on va voir
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    #nginx ne comprend pas le php donc on fait passer les fichier .php
    #au wordpress
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:${WORDPRESS_PORT};
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}